apiVersion: v1
kind: Service
metadata:
  name: webapplicationfx-http-service
  namespace: default
  annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: webapplicationfx-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
